name: ds
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  infinite_scroll_pagination: ^4.1.0
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0

  cdn:
    path: ../cdn

  utils:
    path: ../utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: vSFProText
      fonts:
        - asset: assets/fonts/SF/SF-Pro-Text-Black.otf
          weight: 900
        - asset: assets/fonts/SF/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF/SF-Pro-Text-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF/SF-Pro-Text-Thin.otf
          weight: 100
    - family: vFSBeauSansPro
      fonts:
        - asset: assets/fonts/FS/FS-PFBeauSansPro-Black.otf
          weight: 900
        - asset: assets/fonts/FS/FS-PFBeauSansPro-Bold.otf
          weight: 700
        - asset: assets/fonts/FS/FS-PFBeauSansPro-SemiBold.otf
          weight: 600
        - asset: assets/fonts/FS/FS-PFBeauSansPro-Bbook.otf
          weight: 500
        - asset: assets/fonts/FS/FS-PFBeauSansPro-Regular.otf
          weight: 400
        - asset: assets/fonts/FS/FS-PFBeauSansPro-Light.otf
          weight: 300
        - asset: assets/fonts/FS/FS-PFBeauSansPro-Thin.otf
          weight: 100
